# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabriel B Borges
email: gborges0727@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website! You can find information on me 
  as well as my CV listed here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabeborges.com" # the base hostname & protocol for your site
twitter_username: gborges0727
github_username:  gborges0727

# Build settings
markdown: kramdown
